specVersion: 0.0.4
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: rocketVault
    network: mainnet
    source:
      address: '0x3bDC69C4E5e13E52A65f5583c23EFB9636b469d6'
      abi: RocketVault
      startBlock: 13325238
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/RocketPool.ts
      entities:
        - Token
        - Pool
        - Minipool
        - PoolDailySnapshot
        - PoolHourlySnapshot
        - Protocol
        - FinancialsDailySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
      abis:
        ###########################################
        ######## RocketPool Generic ABIs ##########
        ###########################################
        - name: DepositPool
          file: ./abis/depositpool.json
        - name: RocketStorage
          file: ./abis/rocketStorage.json
        - name: RocketVault
          file: ./abis/rocketVault.json
        - name: RETH
          file: ./abis/reth.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: rocketNetworkBalances
          file: ./abis/rocketNetworkBalances.json
        - name: rocketNetworkFees
          file: ./abis/rocketNetworkFees.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: EtherDeposited(indexed string,uint256,uint256)
          handler: handleEtherDeposit
        - event: EtherWithdrawn(indexed string,uint256,uint256)
          handler: handleEtherWithdrawn
  - kind: ethereum
    name: rocketNetworkBalances
    network: mainnet
    source:
      address: '0x138313f102cE9a0662F826fCA977E3ab4D6e5539'
      abi: rocketNetworkBalances
      startBlock: 13325238
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/RocketPool.ts
      entities:
        - Token
        - Pool
        - Minipool
        - PoolDailySnapshot
        - PoolHourlySnapshot
        - Protocol
        - FinancialsDailySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
      abis:
        ###########################################
        ######## RocketPool Generic ABIs ##########
        ###########################################
        - name: DepositPool
          file: ./abis/depositpool.json
        - name: RocketStorage
          file: ./abis/rocketStorage.json
        - name: RocketVault
          file: ./abis/rocketVault.json
        - name: RETH
          file: ./abis/reth.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: rocketNodeDeposit
          file: ./abis/rocketNodeDeposit.json
        - name: rocketNetworkBalances
          file: ./abis/rocketNetworkBalances.json
        - name: rocketNetworkFees
          file: ./abis/rocketNetworkFees.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: BalancesUpdated(uint256,uint256,uint256,uint256,uint256)
          handler: handleBalanceUpdate
  - kind: ethereum
    name: rocketNodeStaking
    network: mainnet
    source:
      address: '0x3019227b2b8493e45Bf5d25302139c9a2713BF15'
      abi: rocketNodeStaking
      startBlock: 13325238
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/RocketPool.ts
      entities:
        - Token
        - Pool
        - Minipool
        - PoolDailySnapshot
        - PoolHourlySnapshot
        - Protocol
        - FinancialsDailySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
      abis:
        ###########################################
        ######## RocketPool Generic ABIs ##########
        ###########################################
        - name: DepositPool
          file: ./abis/depositpool.json
        - name: RocketStorage
          file: ./abis/rocketStorage.json
        - name: RocketVault
          file: ./abis/rocketVault.json
        - name: RETH
          file: ./abis/reth.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: rocketNodeDeposit
          file: ./abis/rocketNodeDeposit.json
        - name: rocketNetworkBalances
          file: ./abis/rocketNetworkBalances.json
        - name: rocketNetworkFees
          file: ./abis/rocketNetworkFees.json
        - name: rocketNodeStaking
          file: ./abis/rocketNodeStaking.json
        - name: rocketNetworkPrices
          file: ./abis/rocketNetworkPrices.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: RPLStaked(indexed address,uint256,uint256)
          handler: handleRPLStaked
        - event: RPLWithdrawn(indexed address,uint256,uint256)
          handler: handleRPLWithdrawn
        - event: RPLSlashed(indexed address,uint256,uint256,uint256)
          handler: handleRPLSlashed
  - kind: ethereum
    name: rocketMinipoolQueue
    network: mainnet
    source:
      address: '0x5870dA524635D1310Dc0e6F256Ce331012C9C19E'
      abi: rocketMinipoolQueue
      startBlock: 13325238
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      file: ./src/mappings/RocketPool.ts
      entities:
        - Token
        - Pool
        - Minipool
        - PoolDailySnapshot
        - PoolHourlySnapshot
        - Protocol
        - FinancialsDailySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
      abis:
        ###########################################
        ######## RocketPool Generic ABIs ##########
        ###########################################
        - name: DepositPool
          file: ./abis/depositpool.json
        - name: RocketStorage
          file: ./abis/rocketStorage.json
        - name: RocketVault
          file: ./abis/rocketVault.json
        - name: RETH
          file: ./abis/reth.json
        - name: ERC20
          file: ./abis/ERC20.json
        - name: rocketNodeDeposit
          file: ./abis/rocketNodeDeposit.json
        - name: rocketNetworkBalances
          file: ./abis/rocketNetworkBalances.json
        - name: rocketNetworkFees
          file: ./abis/rocketNetworkFees.json
        - name: rocketNodeStaking
          file: ./abis/rocketNodeStaking.json
        - name: rocketNetworkPrices
          file: ./abis/rocketNetworkPrices.json
        - name: rocketMinipoolQueue
          file: ./abis/rocketMinipoolQueue.json

        ###########################################
        ############## Price Oracle ###############
        ###########################################
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CurvePoolRegistry
          file: ./abis/Prices/Curve/PoolRegistry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
        # SushiSwap Contracts
        - name: SushiSwapRouter
          file: ./abis/Prices/SushiSwap/Router.json
        - name: SushiSwapFactory
          file: ./abis/Prices/SushiSwap/Factory.json
        - name: SushiSwapPair
          file: ./abis/Prices/SushiSwap/Pair.json
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
      eventHandlers:
        - event: MinipoolEnqueued(indexed address,indexed bytes32,uint256)
          handler: handleMinipoolEnqueued
        - event: MinipoolRemoved(indexed address,indexed bytes32,uint256)
          handler: handleMinipoolRemoved
        - event: MinipoolDequeued(indexed address,indexed bytes32,uint256)
          handler: handleMinipoolDequeued
